/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.cma.gcvms.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.cma.gcvms.domain.Dept;
import com.cma.gcvms.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link Dept} 
 */
@Named
@Singleton
public class DeptRepository extends GenericRepository<Dept, Integer> {

    public DeptRepository() {
        super(Dept.class);
    }

    @Override
    public Dept getNew() {
        return new Dept();
    }

    @Override
    public Dept getNewWithDefaults() {
        return getNew().withDefaults();
    }
}