/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.cma.gcvms.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.cma.gcvms.domain.Employee;
import com.cma.gcvms.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link Employee} 
 */
@Named
@Singleton
public class EmployeeRepository extends GenericRepository<Employee, Integer> {

    public EmployeeRepository() {
        super(Employee.class);
    }

    @Override
    public Employee getNew() {
        return new Employee();
    }

    @Override
    public Employee getNewWithDefaults() {
        return getNew().withDefaults();
    }
}