/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.cma.gcvms.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.cma.gcvms.domain.VehicleTyp;
import com.cma.gcvms.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link VehicleTyp} 
 */
@Named
@Singleton
public class VehicleTypRepository extends GenericRepository<VehicleTyp, Integer> {

    public VehicleTypRepository() {
        super(VehicleTyp.class);
    }

    @Override
    public VehicleTyp getNew() {
        return new VehicleTyp();
    }

    @Override
    public VehicleTyp getNewWithDefaults() {
        return getNew().withDefaults();
    }
}