/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.cma.gcvms.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.cma.gcvms.domain.Dept;
import com.cma.gcvms.printer.DeptPrinter;
import com.cma.gcvms.repository.DeptRepository;
import com.cma.gcvms.web.domain.support.GenericController;
import com.cma.gcvms.web.permission.DeptPermission;

/**
 * Stateless controller for {@link Dept} conversation start.
 */
@Named
@Singleton
public class DeptController extends GenericController<Dept, Integer> {
    public static final String DEPT_EDIT_URI = "/domain/deptEdit.faces";
    public static final String DEPT_SELECT_URI = "/domain/deptSelect.faces";

    @Inject
    public DeptController(DeptRepository deptRepository, DeptPermission deptPermission, DeptPrinter deptPrinter) {
        super(deptRepository, deptPermission, deptPrinter, DEPT_SELECT_URI, DEPT_EDIT_URI);
    }
}