/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.cma.gcvms.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.cma.gcvms.domain.Dept;
import com.cma.gcvms.web.domain.support.GenericExcelExporter;
import com.cma.gcvms.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Dept} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class DeptExcelExporter extends GenericExcelExporter<Dept> {
    @Inject
    protected DeptSearchForm sf;

    public DeptExcelExporter() {
        super("dept_name");
    }

    @Override
    protected void fillResultItem(int row, Dept item) {
        int col = 0;
        setValue(row, col++, item.getName());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "dept_name", sf.getNameSelector());
    }
}