/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.cma.gcvms.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.cma.gcvms.domain.Employee;
import com.cma.gcvms.printer.EmployeePrinter;
import com.cma.gcvms.repository.EmployeeRepository;
import com.cma.gcvms.web.domain.support.GenericController;
import com.cma.gcvms.web.permission.EmployeePermission;

/**
 * Stateless controller for {@link Employee} conversation start.
 */
@Named
@Singleton
public class EmployeeController extends GenericController<Employee, Integer> {
    public static final String EMPLOYEE_EDIT_URI = "/domain/employeeEdit.faces";
    public static final String EMPLOYEE_SELECT_URI = "/domain/employeeSelect.faces";

    @Inject
    public EmployeeController(EmployeeRepository employeeRepository, EmployeePermission employeePermission, EmployeePrinter employeePrinter) {
        super(employeeRepository, employeePermission, employeePrinter, EMPLOYEE_SELECT_URI, EMPLOYEE_EDIT_URI);
    }
}