/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.cma.gcvms.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.cma.gcvms.domain.Municipality;
import com.cma.gcvms.repository.MunicipalityRepository;
import com.cma.gcvms.web.domain.support.GenericEditForm;
import com.cma.gcvms.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Municipality}.
 */
@Named
@ConversationContextScoped
public class MunicipalityEditForm extends GenericEditForm<Municipality, Integer> {
    @Inject
    protected MunicipalityController municipalityController;

    @Inject
    public MunicipalityEditForm(MunicipalityRepository municipalityRepository) {
        super(municipalityRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Municipality getMunicipality() {
        return getEntity();
    }

    public String print() {
        return municipalityController.print(getMunicipality());
    }
}
