/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.cma.gcvms.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.cma.gcvms.domain.Municipality;
import com.cma.gcvms.printer.MunicipalityPrinter;
import com.cma.gcvms.repository.MunicipalityRepository;
import com.cma.gcvms.web.domain.support.GenericController;
import com.cma.gcvms.web.permission.MunicipalityPermission;

/**
 * Stateless controller for {@link Municipality} conversation start.
 */
@Named
@Singleton
public class MunicipalityController extends GenericController<Municipality, Integer> {
    public static final String MUNICIPALITY_EDIT_URI = "/domain/municipalityEdit.faces";
    public static final String MUNICIPALITY_SELECT_URI = "/domain/municipalitySelect.faces";

    @Inject
    public MunicipalityController(MunicipalityRepository municipalityRepository, MunicipalityPermission municipalityPermission,
            MunicipalityPrinter municipalityPrinter) {
        super(municipalityRepository, municipalityPermission, municipalityPrinter, MUNICIPALITY_SELECT_URI, MUNICIPALITY_EDIT_URI);
    }
}