/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.cma.gcvms.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.cma.gcvms.domain.Municipality;
import com.cma.gcvms.repository.MunicipalityRepository;
import com.cma.gcvms.web.domain.support.GenericLazyDataModel;
import com.cma.gcvms.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Municipality}
 */
@Named
@ConversationContextScoped
public class MunicipalityLazyDataModel extends GenericLazyDataModel<Municipality, Integer, MunicipalitySearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public MunicipalityLazyDataModel(MunicipalityRepository municipalityRepository, MunicipalityController municipalityController,
            MunicipalitySearchForm municipalitySearchForm, MunicipalityExcelExporter municipalityExcelExporter) {
        super(municipalityRepository, municipalityController, municipalitySearchForm, municipalityExcelExporter);
    }
}