/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 */
package com.cma.gcvms.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.cma.gcvms.domain.Vehicle;
import com.cma.gcvms.repository.VehicleRepository;
import com.cma.gcvms.repository.support.EntityGraphLoader;

/**
 * Preloads the {@link Vehicle} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class VehicleGraphLoader extends EntityGraphLoader<Vehicle, Integer> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected VehicleGraphLoader() {
        super();
    }

    @Inject
    public VehicleGraphLoader(VehicleRepository vehicleRepository) {
        super(vehicleRepository);
    }

    @Override
    public void loadGraph(Vehicle vehicle) {
        loadSingular(vehicle.getTyp());
    }
}