/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.cma.gcvms.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Route.class)
public abstract class Route_ {

    // Raw attributes
    public static volatile SingularAttribute<Route, Integer> id;
    public static volatile SingularAttribute<Route, String> name;
    public static volatile SingularAttribute<Route, Double> distance;
    public static volatile SingularAttribute<Route, String> startLoc;
    public static volatile SingularAttribute<Route, String> endLoc;
    public static volatile SingularAttribute<Route, Integer> createdBy;
    public static volatile SingularAttribute<Route, Date> createdDate;
}